// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSZKzbN3yb5DKKWUQ1vYYK-nJseZpIBqU',
    appId: '1:368595359520:web:46117c6edc0ced83d9e945',
    messagingSenderId: '368595359520',
    projectId: 'estateverify-bbe12',
    authDomain: 'estateverify-bbe12.firebaseapp.com',
    storageBucket: 'estateverify-bbe12.firebasestorage.app',
    measurementId: 'G-EBWGH3MDZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArfifAxeSi_TvNzs6XCW37eC6_vTJ0UCQ',
    appId: '1:368595359520:android:11be4fb06ff03531d9e945',
    messagingSenderId: '368595359520',
    projectId: 'estateverify-bbe12',
    storageBucket: 'estateverify-bbe12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9SZmcsy6j4hsjGSXUlx-fOngXmAaRCAE',
    appId: '1:368595359520:ios:f9a49792148d8c3fd9e945',
    messagingSenderId: '368595359520',
    projectId: 'estateverify-bbe12',
    storageBucket: 'estateverify-bbe12.firebasestorage.app',
    iosBundleId: 'com.example.realEstateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSZKzbN3yb5DKKWUQ1vYYK-nJseZpIBqU',
    appId: '1:368595359520:web:54b8df07a3fb85fed9e945',
    messagingSenderId: '368595359520',
    projectId: 'estateverify-bbe12',
    authDomain: 'estateverify-bbe12.firebaseapp.com',
    storageBucket: 'estateverify-bbe12.firebasestorage.app',
    measurementId: 'G-HCZFBN7BEG',
  );
}
